Add E2E test
ca-dp/bucketeer-ios-sdk pull request #88
Opened 2022-10-22 12:56 UTC by jinSasaki

- Fix bugs
- Add E2E test

@cre8ivejp 
Please let me know if there are any E2E test cases you would like to see. 🙏

2022-10-25 03:30 UTC, cre8ivejp requested changes

2022-10-25 03:30 UTC, cre8ivejp commented on Bucketeer2/Sources/Public/BKTClient.swift
> +    public static func initialize(config: BKTConfig, user: BKTUser, timeoutMillis: Int64 = 5000, completion: ((BKTError?) -> Void)?) {
Is it possible to implement it using async?

E.g.
```swift
initialize(config: BKTConfig, user: BKTUser, timeoutMillis: Int64 = 5000) async throws BKTError

// Await
let initError = try await BKTClient.initialize(config, user, timeoutMillis)
if initError != nil {
  ...
}

// Non-await
BKTClient.initialize(config, user)
```

2022-10-29 02:22 UTC, jinSasaki commented on Bucketeer2Tests/BKTClientImplTests.swift
> -final class BKTClientImplTests: XCTestCase {
Fixed https://github.com/ca-dp/bucketeer-ios-sdk/pull/88/commits/bb52db5460b6543bafe53eefa109d9cf45e58218

2022-10-29 02:22 UTC, jinSasaki commented on Bucketeer2/Sources/Public/BKTUser.swift
> +    public mutating func custom(attributes: [String: String]) {
Fixed https://github.com/ca-dp/bucketeer-ios-sdk/pull/88/commits/b2787ded1b33614087e34fdef84a0e5df35fe615

2022-10-29 02:22 UTC, jinSasaki commented on Bucketeer2/Sources/Public/BKTClient.swift
> +    public func evaluationDetails(featureId: String, completion: ((BKTEvaluation?) -> Void)?) {
Fixed https://github.com/ca-dp/bucketeer-ios-sdk/pull/88/commits/10c68279e05b9c2a12896c4145b8b3c63bc156d3

2022-10-29 02:23 UTC, jinSasaki commented on Bucketeer2/Sources/Public/BKTClient.swift
> +            config.logger?.warn(message: "BKTClient is already initialized. not sure if initial fetch has been finished")
Fixed https://github.com/ca-dp/bucketeer-ios-sdk/pull/88/commits/d044a3755ee73d42fbf5a97fcf1c68c5f8f18efd

2022-10-29 02:27 UTC, jinSasaki commented on Bucketeer2/Sources/Public/BKTClient.swift
> +            client.refreshCache()
Fixed https://github.com/ca-dp/bucketeer-ios-sdk/pull/88/commits/9dd84589018bbd73df023be7c2ce53c71d22c872

2022-10-29 02:30 UTC, jinSasaki commented
Use feature flags of `sdke2e` project instead of the individual project. https://github.com/ca-dp/bucketeer-ios-sdk/pull/88/commits/a5edeff637f0554bf4446d52c9457f0a16a4ecc7

2022-10-31 03:48 UTC, cre8ivejp commented on Bucketeer2/Sources/Public/BKTClient.swift
> +    public static func initialize(config: BKTConfig, user: BKTUser, timeoutMillis: Int64 = 5000, completion: ((BKTError?) -> Void)?) {
Let's keep it as it is.
Thanks.

2022-11-03 06:47 UTC, jinSasaki commented
@cre8ivejp 
The tests have been passed just now, so please review.
Sorry too late. 🙇

2022-11-07 08:07 UTC, cre8ivejp approved these changes
Excellent!
Thank you!

2022-11-12 01:14 UTC, merged